### PR TITLE
Added UC Browser

### PR DESCRIPTION
**Pull request by firewalker06**
This PR will add `.uc_browser?` method for detecting UC Browser.
Source: http://www.ucweb.com/download/UCBrowser_User_Agent_en.pdf

### CODE REVIEW

**Comment by balvig** [comment]
+1 !

**Comment by DevilalDheer** [comment]
@firewalker06 :+1:  ,
Team, Please merge this PR.

**Comment by fnando** [comment]
Implemented by dfa59859. Thanks and sorry for taking this long.

**Comment by firewalker06** [comment]
Thanks @fnando  :+1:

**Pull request closed without merging**
