### PR TITLE
Adding more bots (and ignoring some bundler stuff)

### PR DESCRIPTION
**Pull request by avand**
Looked through the user agent for many days of high traffic for my site (mysteryscience.com) scanning for the word "bot." Added my findings to `bots.yml`.

### CODE REVIEW

**Comment by nativestranger** [comment]
bump!

**Comment by avand** [comment]
@fnando: Would love to have this merged in if you've got the time.

**Comment by Yenwod** [comment]
bump :+1:

**Comment by avand** [comment]
Merged in the latest and resolved conflicts so this is good to go! Would love a merge. Thanks!

**Comment by nativestranger** [comment]
@avand Maybe @fnando will merge this in sooner if you update the bots test like this for each new bot - https://github.com/fnando/browser/commit/901a7087f51d0449a3a18a30b013d4d44a23f20f

@fnando Any input on this branch?

**Comment by avand** [comment]
Will do! Out of curiosity, what's the value of these test? Haven't dug deep here but looks like we're just duplicating the user agent in the test and that the tests are just a confirmation of what's in the bots.yml.

**Comment by nativestranger** [comment]
@avand Yea, the tests appear to just be confirming that the user agents in bots.yml are marked as bots. So I guess they're just to ensure that things are working expected. I'm not sure if @fnando is requiring new bots to have these tests, but I noticed the last 3 pull requests he merged all updated these tests for the bots they added. So I figured it's worth a shot. ¯\_(ツ)_/¯

**Comment by avand** [comment]
Ah, that makes good sense. So `bots.yml` is more of the pattern to match on and `ua.yml` is the full user agent. That's actually a problem for me because I didn't save the full user agents of those bots. I'll see what I can find.

**Comment by avand** [comment]
I started Googling for user agents for each of these bots and got through about 5 of them and realized that this was incredibly tedious and I'm not sure it really provides much value. Notably, most of the bots in `bots.yml` are not tested. So I'm inclined to wait until @fnando at least chimes in before doing all this copy/paste work.

**Comment by nativestranger** [comment]
@avand Good call, and thanks for the speedy response!

**Comment by peteygao** [comment]
This is pretty useful and contains a lot of bots that we're seeing as well. I was just about to open a PR for detecting some of the bots listed here (e.g. `UptimeRobo`), so it'd be great to see this merged soon.

**Comment by fnando** [comment]
These tests aren't that important; is more of a sanity check for the most important robots like Google Bot. You don't have to add other robots to the list.

Since you're just updating the bots list, there's no problem in merging this… which I just did.

**Comment by avand** [comment]
Thanks @fnando! Any idea when you'll cut a new version of the gem with these changes? I'd love to point our Gemfile back.

**Pull request closed without merging**
