### PR TITLE
fixed chrome detection (yandex was determined as chrome)

### PR DESCRIPTION
**Pull request by proton**
There are problem for yandex browser because browser.chrome? returns true.

### CODE REVIEW

**Comment by fnando** [comment]
Hello, @proton! This is your first Pull Request that will be reviewed by [Ebert](https://ebertapp.io/), an automatic Code Review service. It will leave comments on this diff with potential issues and style violations found in the code as you push new commits. You can also see all the issues found on this Pull Request on its [review page](https://ebertapp.io/github/fnando/browser/pulls/293). Please check our [documentation](https://ebertapp.io/docs) for more information.

**Comment by prodis** [comment]
Missing adjust unit test:
https://github.com/fnando/browser/blob/master/test/unit/chrome_test.rb#L51

**Comment by proton** [comment]
@prodis how to run test?
`$ bundle exec rake`
`/home/proton/.rvm/rubies/ruby-2.1.5/bin/ruby -I"lib:lib:test" -rubygems -I"/home/proton/.rvm/gems/ruby-2.1.5@global/gems/rake-12.0.0/lib" "/home/proton/.rvm/gems/ruby-2.1.5@global/gems/rake-12.0.0/lib/rake/rake_test_loader.rb" "test/browser_test.rb" "test/middleware_test.rb" "test/rails_test.rb" "test/unit/accept_language_test.rb" "test/unit/adobe_air_test.rb" "test/unit/alipay_test.rb" "test/unit/android_test.rb" "test/unit/blackberry_test.rb" "test/unit/bots_test.rb" "test/unit/chrome_test.rb" "test/unit/console_test.rb" "test/unit/device_test.rb" "test/unit/firefox_test.rb" "test/unit/generic_test.rb" "test/unit/ie_test.rb" "test/unit/ios_app_test.rb" "test/unit/ios_test.rb" "test/unit/kindle_test.rb" "test/unit/meta_test.rb" "test/unit/micro_messenger_test.rb" "test/unit/nokia_test.rb" "test/unit/opera_test.rb" "test/unit/platform_test.rb" "test/unit/proxy_test.rb" "test/unit/qq_test.rb" "test/unit/safari_test.rb" "test/unit/uc_browser_test.rb" "test/unit/weibo_test.rb" "test/unit/windows_phone_test.rb" "test/unit/windows_test.rb" `
`W, [2017-04-12T21:51:39.684931 #22987]  WARN -- :       This usage of the Code Climate Test Reporter is now deprecated. Since version
      1.0, we now require you to run `SimpleCov` in your test/spec helper, and then
      run the provided `codeclimate-test-reporter` binary separately to report your
      results to Code Climate.

      More information here: https://github.com/codeclimate/ruby-test-reporter/blob/master/README.md`

`rake aborted!`
`Command failed with status (1): [ruby -I"lib:lib:test" -rubygems -I"/home/proton/.rvm/gems/ruby-2.1.5@global/gems/rake-12.0.0/lib" "/home/proton/.rvm/gems/ruby-2.1.5@global/gems/rake-12.0.0/lib/rake/rake_test_loader.rb" "test/browser_test.rb" "test/middleware_test.rb" "test/rails_test.rb" "test/unit/accept_language_test.rb" "test/unit/adobe_air_test.rb" "test/unit/alipay_test.rb" "test/unit/android_test.rb" "test/unit/blackberry_test.rb" "test/unit/bots_test.rb" "test/unit/chrome_test.rb" "test/unit/console_test.rb" "test/unit/device_test.rb" "test/unit/firefox_test.rb" "test/unit/generic_test.rb" "test/unit/ie_test.rb" "test/unit/ios_app_test.rb" "test/unit/ios_test.rb" "test/unit/kindle_test.rb" "test/unit/meta_test.rb" "test/unit/micro_messenger_test.rb" "test/unit/nokia_test.rb" "test/unit/opera_test.rb" "test/unit/platform_test.rb" "test/unit/proxy_test.rb" "test/unit/qq_test.rb" "test/unit/safari_test.rb" "test/unit/uc_browser_test.rb" "test/unit/weibo_test.rb" "test/unit/windows_phone_test.rb" "test/unit/windows_test.rb" ]
/home/proton/.rvm/gems/ruby-2.1.5@global/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/proton/.rvm/gems/ruby-2.1.5@tmp/bin/ruby_executable_hooks:15:in `eval'
/home/proton/.rvm/gems/ruby-2.1.5@tmp/bin/ruby_executable_hooks:15:in `<main>'`
`Tasks: TOP => default => test
`(See full trace by running task with --trace)`
`

**Comment by prodis** [comment]
@proton Do the same I did in this commit: https://github.com/fnando/browser/pull/285/commits/309da0ad781dc219ec96bc4f1a6437dc7633365b

I fixed a long time ago, but no merge for me until now. 😴 😄

**Comment by fnando** [comment]
Ebert has finished reviewing this Pull Request and has found:

* 2 possible new issues (including those that may have been commented here).

You can see more details about this review at https://ebertapp.io/github/fnando/browser/pulls/293.

**Comment by fnando** [comment]
Fixed upstream. Closing this due to all conflicts.

**Pull request closed without merging**
