### PR TITLE
Add Google Search App support

### PR DESCRIPTION
**Pull request by milandobrota**

### CODE REVIEW

**Comment by milandobrota** [comment]
@fnando The build seems to be failing because of Rubocop, but I can't reproduce it locally (and it seems to be complaining about the files that I haven't changed as part of this PR).

**Comment by fnando** [comment]
@milandobrota just pushed latest Rubocop fixes to master. Can you please rebase?

**Comment by milandobrota** [comment]
@fnando Hey it looks like we pushed at the same time. :)

**Comment by milandobrota** [comment]
@fnando It looks like it passed anyway. :)

**Comment by fnando** [comment]
@milandobrota yeah, sorry for tainting your branch. I have some time to work on this right now, and didn't want to wait. :O

**Comment by milandobrota** [comment]
No problem!

**Pull request merged**
