### PR TITLE
#183 Detecting Yandex.Browser

### PR DESCRIPTION
**Pull request by stereodenis**

### CODE REVIEW

**Comment by stereodenis** [comment]
@fnando is this enough?

**Comment by fnando** [comment]
To be honest, I don't think every single browser should have a method. Since it uses Chrome's engine (which is advertised by its user agent), why do you need to target Yandex? Give me a good reason. :)

**Comment by stereodenis** [comment]
@fnando in our project we need to detect YandexBrowser, but not Chrome. Maybe others need this too

**Comment by stereodenis** [comment]
@fnando thnx!

**Comment by AlexWayfer** [comment]
Will this code also triggered for Yandex Search Engine? I didn't find Yandex in the `search_engines.yml` file, and I don't have Yandex Search Engine User-Agent.

**Pull request closed without merging**
