### PR TITLE
Add NewRelic pinger and SocialRank.io user agent in bot list

### PR DESCRIPTION
**Pull request by vincent-pochet**
Add bot detection for NewRelicPinger and SocialRankIO

### CODE REVIEW

**Comment by fnando** [comment]
Hello, @vincent-pochet! This is your first Pull Request that will be reviewed by [Ebert](https://ebertapp.io/), an automatic Code Review service. It will leave comments on this diff with potential issues and style violations found in the code as you push new commits. You can also see all the issues found on this Pull Request on its [review page](https://ebertapp.io/github/fnando/browser/pulls/284). Please check our [documentation](https://ebertapp.io/docs) for more information.

**Comment by vincent-pochet** [comment]
Maybe I missing something, but I don't get why tests are broken on travis.

**Comment by prodis** [comment]
@vincent-pochet 
Tests are broken on Travis because the new way Code Climate works.

```
W, [2016-12-14T14:32:11.778793 #4060]  WARN -- :       This usage of the Code Climate Test Reporter is now deprecated. Since version
      1.0, we now require you to run `SimpleCov` in your test/spec helper, and then
      run the provided `codeclimate-test-reporter` binary separately to report your
      results to Code Climate.

      More information here: https://github.com/codeclimate/ruby-test-reporter/blob/master/README.md
```

I fixed it in another PR: https://github.com/fnando/browser/pull/285/commits/309da0ad781dc219ec96bc4f1a6437dc7633365b

**Comment by vincent-pochet** [comment]
Thank you @prodis :)

**Pull request merged**
