### PR TITLE
Add BUbiNG bot

### PR DESCRIPTION
**Pull request by AlexWayfer**
We received a request to `/robots.txt` from UA `BUbiNG (+http://law.di.unimi.it/BUbiNG.html)`.

### CODE REVIEW

**Comment by renchap** [comment]
We also see it more and more since a few days, it would be great to have it auto-detected as a bot.

**Comment by renchap** [comment]
There is another version around: `Barkrowler/0.7 (+http://www.exensa.com/crawl)`. From their web page:
> Barkrowler is our experimental and very fresh version of the BUbiNG crawler (it's basically BUbiNG with our pull requests applied and the right configuration for distribution on EC2)

**Comment by AlexWayfer** [comment]
@renchap, I'm not sure that another version (fork) of bot with absolutely different UA should be added in this PR.

**Comment by AlexWayfer** [comment]
@renchap, I've created #335 for this. We got it too.

**Pull request merged**
