### PR TITLE
update bots.yml

### PR DESCRIPTION
**Pull request by ibarria0**
Add whatsapp bot

### CODE REVIEW

**Comment by fnando** [comment]
Hello, @ibarria0! This is your first Pull Request that will be reviewed by [Ebert](https://ebertapp.io/), an automatic Code Review service. It will leave comments on this diff with potential issues and style violations found in the code as you push new commits. You can also see all the issues found on this Pull Request on its [review page](https://ebertapp.io/github/fnando/browser/pulls/316). Please check our [documentation](https://docs.ebertapp.io) for more information.

**Comment by fnando** [comment]
Can you please follow this instructions? 

https://github.com/fnando/browser/blob/master/README.md#adding-a-new-bot

**Comment by ibarria0** [comment]
Done. Sorry about that.

**Comment by fnando** [comment]
Thanks! Closed via #317

**Pull request closed without merging**
