### PR TITLE
Detect IE/Edge versions based on compatibility view.

### LINKED ISSUE #51: Real version Internet Explorer in Compatibility View
Browser: Internet Explorer 10

default:
**browser.version: 10**
request.env['HTTP_USER_AGENT']: Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/6.0)

compatibility view:
**browser.version: 7**
request.env['HTTP_USER_AGENT']: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; Trident/6.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.3; Tablet PC 2.0; .NET4.0C; .NET4.0E)

I need a method to determine the real version browser. 
Maybe add some method for this?

I think for that you can check the layout engine (Trident version).

### PR DESCRIPTION
**Pull request by fnando**
The big change here is that Browser#version and Browser#full_version will always return the real browser version. If you want the compatibility view version, you can get it with Browser#msie_version and Browser#msie_full_version.

Another change is that IE/Edge are considered modern browsers only when not runnnig in compatibility view mode. If you need to change this behavior, create your own Browser.modern_rules.

Closes #51.

### CODE REVIEW

**Comment by stanhu** [comment]
Just tried it out. Works like a charm. Thanks!

**Comment by stanhu** [comment]
Just a friendly reminder that it would be nice to have a release with this PR. Thanks!

**Comment by fnando** [comment]
@stanhu just released v1.0.0.

**Comment by stanhu** [comment]
@fnando Thanks!

**Pull request merged**
