### PR TITLE
Add Samsung Browser.

### PR DESCRIPTION
**Pull request by milandobrota**
Currently, the Samsung Browser gets incorrectly recognized as Chrome. This PR fixes that.

### CODE REVIEW

**Comment by fnando** [comment]
Hey! Thanks for this. Can you also add an entry to the changelog?

**Comment by milandobrota** [comment]
@fnando Done!

**Comment by milandobrota** [comment]
@fnando Or did you want me to create a new version?

**Comment by fnando** [comment]
I added a few missing things. I hope you don't mind.

**Comment by milandobrota** [comment]
@fnando Perfect! Thanks!

**Pull request merged**
