### PR TITLE
Add WatchSumo

### PR DESCRIPTION
**Pull request by zeto**
Add http://www.watchsumo.com to Bot list

### CODE REVIEW

**Comment by fnando** [comment]
Sorry for the delay on replying this. Can you follow [these instructions](https://github.com/fnando/browser#adding-a-new-bot)?

**Comment by zeto** [comment]
@fnando Sure, added.

**Comment by pusewicz** [comment]
Will this work when the version number of the User Agent changes?

**Comment by pusewicz** [comment]
Also, hi @zeto!

**Comment by zeto** [comment]
Halo @pusewicz :)

I think so.

See: https://github.com/fnando/browser/blob/master/lib/browser/bot.rb#L57 (Eg. If user agent contains "watchsumo"

**Pull request merged**
